# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiPceN98jZ_h4nhnpoH7CY0v-waMVc7A
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# from datetime import datetime
# 
# st.set_page_config(
#     page_title="Dashboard Comercio Mundial",layout="wide")
# 
# 
# st.title("Dashboard de Análisis de Comercio Mundial")
# 
# with open("styles.css") as f:
#     st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
# 
# @st.cache_data
# def load_data():
# 
#     df = pd.read_csv("cleaned_world_export_import.csv")
# 
#     if 'Year' in df.columns:
#         df['Year'] = pd.to_numeric(df['Year'], errors='coerce').astype('Int64')
# 
#     df['Decade'] = (df['Year'] // 10) * 10
# 
#     return df
# 
# try:
#     df = load_data()
#     st.success(f"Datos cargados correctamente: {len(df)} registros.")
# except Exception as e:
#     st.error(f"Error al cargar los datos: {e}")
#     st.stop()
# 
# tab1, tab2, tab3, tab4 = st.tabs([
#     "Evolución en el Tiempo",
#     "Análisis por País/Mapa",
#     "Análisis de Comercio por País",
#     "Exportaciones vs Importaciones"
# ])
# 
# 
# with tab1:
# 
#     st.subheader("Evolución de Ventas en el Tiempo")
# 
#     gra1_col1, gra1_col2 = st.columns([3, 1])
# 
#     with gra1_col1:
#         metric_type = st.selectbox("Selecciona el tipo de métrica:",
#                                    ["Export (US$ Thousand)", "Import (US$ Thousand)", "World Growth (%)"])
# 
#     with gra1_col2:
#         time_grouping = st.selectbox("Agrupar por:", ["Año", "Década"])
# 
#     metric_map = {
#         "Export (US$ Thousand)": "Export (US$ Thousand)",
#         "Import (US$ Thousand)": "Import (US$ Thousand)",
#         "World Growth (%)": "World Growth (%)"
#     }
# 
#     time_map = {
#         "Año": "Year",
#         "Década": "Decade"
#     }
# 
#     sort_time_met = metric_map[metric_type]
#     sort_time_gro = time_map[time_grouping]
# 
#     df_time = df.groupby(sort_time_gro).agg({
#         sort_time_met: "sum"
#     }).reset_index()
# 
#     with gra1_col1:
#         fig = px.line(df_time, x=sort_time_gro, y=sort_time_met,
#                       title=f"Evolución de {metric_type} por {time_grouping.lower()}", markers=True)
# 
#     fig.update_layout(
#     paper_bgcolor="rgba(0,0,0,0)",
#     plot_bgcolor="rgba(0,0,0,0)",
#     font=dict(color="white"),
#     title=dict(font=dict(color="white"))
# )
# 
#     fig.update_xaxes(showgrid=False)
#     fig.update_yaxes(showgrid=False)
# 
#     st.plotly_chart(fig, use_container_width=True)
# 
# 
# with tab2:
# 
#     st.subheader("Análisis por Paises")
# 
#     col_left, col_right = st.columns([1, 1])
# 
#     with col_left:
#       selected_country = st.selectbox(
#           "Selecciona un país:",
#            sorted(df["Partner Name"].unique())
#         )
# 
#     with col_right:
#       tipo = st.selectbox(
#           "Selecciona el tipo de métrica:",
#           ["Exportación", "Importación"]
#         )
# 
#     if tipo == "Exportación":
#         columna = "Export (US$ Thousand)"
#     else:
#         columna = "Import (US$ Thousand)"
# 
# 
#     graph_col, map_col = st.columns([1, 1])
# 
#     with graph_col:
#         country_data = df[df["Partner Name"] == selected_country]
# 
#         df_country = country_data.groupby("Year", as_index=False)[columna].sum()
# 
#         fig_country = px.bar(
#             df_country,
#             x="Year",
#             y=columna,
#             color=columna,
#             color_continuous_scale="Blues",
#             title=f"Evolución de {columna} de {selected_country}")
# 
# 
#         fig_country.update_layout(
#             paper_bgcolor="rgba(0,0,0,0)",
#             plot_bgcolor="rgba(0,0,0,0)",
#             font=dict(color="white"),
#             title=dict(font=dict(color="white"))
#             )
# 
#         st.plotly_chart(fig_country, use_container_width=True)
# 
#     with map_col:
# 
#         df_mapa = df.groupby("Partner Name")[columna].sum().reset_index()
# 
#         fig_mapa = px.choropleth(
#             df_mapa,
#             locations="Partner Name",
#             locationmode="country names",
#             color=columna,
#             color_continuous_scale=["#ffffff", "#cce5ff", "#66b2ff", "#0066cc", "#002147"],
#             title=f"{tipo} Mundial por País",
#             hover_name="Partner Name",
#             hover_data={columna: ":,f"}
# 
#          )
# 
#         fig_mapa.update_layout(
#             geo=dict(
#                 showframe=False,
#                 showcoastlines=False,
#                 projection_type="natural earth"
#             ),
#             paper_bgcolor="rgba(0,0,0,0)",
#             plot_bgcolor="rgba(0,0,0,0)",
#             font=dict(color="white"),
#             title=dict(font=dict(color="white")),
#             legend=dict(font=dict(color="white"))
#         )
# 
#         st.plotly_chart(fig_mapa, use_container_width=True)
# 
# 
#     total_value = country_data[columna].sum()
#     avg_tariff_country = country_data["AHS Simple Average (%)"].mean()
#     avg_growth_country = country_data["World Growth (%)"].mean()
# 
#     st.markdown(f"### Detalle del país seleccionado: **{selected_country}**")
# 
#     colm1, colm2, colm3 = st.columns(3)
#     colm1.metric(f"Total {tipo} (US$ miles)", f"{total_value:,.0f}")
#     colm2.metric("Promedio Arancel (%)", f"{avg_tariff_country:.2f}%")
#     colm3.metric("Crecimiento Mundial Promedio", f"{avg_growth_country:.2f}%")
# 
# 
# 
# with tab3:
# 
#     st.subheader("Análisis de Comercio por País")
# 
#     gra2_col1, gra2_col2 = st.columns(2)
# 
#     with gra2_col1:
#         top_n_countries = st.slider("Selecciona top N países", 5, 30, 15)
# 
#     with gra2_col2:
#         country_metric = st.selectbox("Ordenar por:",
#                                       ["Export (US$ Thousand)",
#                                        "Import (US$ Thousand)",
#                                        "World Growth (%)"])
# 
#     df_countries = df.groupby("Partner Name").agg({
#         "Export (US$ Thousand)": "sum",
#         "Import (US$ Thousand)": "sum",
#         "World Growth (%)": "mean"
#     }).reset_index()
# 
#     df_countries = df_countries.sort_values(country_metric, ascending=False).head(top_n_countries)
# 
#     fig_countries = px.bar(df_countries, y="Partner Name", x=country_metric,
#                            orientation="h", title=f"Top {top_n_countries} países por {country_metric}",
#                            color=country_metric, color_continuous_scale="Sunset")
# 
#     fig_countries.update_layout(yaxis={"categoryorder": "total ascending"})
# 
#     fig_countries.update_layout(
#     paper_bgcolor="rgba(0,0,0,0)",
#     plot_bgcolor="rgba(0,0,0,0)",
#     font=dict(color="white"),
#     title=dict(font=dict(color="white"))
#    )
# 
#     fig_countries.update_xaxes(showgrid=False)
#     fig_countries.update_yaxes(showgrid=False)
# 
#     st.plotly_chart(fig_countries, use_container_width=True)
# 
# 
# 
# with tab4:
# 
#     st.subheader("Distribución Global Exportaciones vs Importaciones")
# 
#     global_totals = {
#         "Exportaciones": df["Export (US$ Thousand)"].sum(),
#         "Importaciones": df["Import (US$ Thousand)"].sum()
#     }
# 
#     df_global = pd.DataFrame(list(global_totals.items()), columns=["Flow", "Amount"])
# 
#     fig_global = px.pie(df_global, values="Amount", names="Flow",
#                         hole=0.5, title="Participación Global de Exportaciones vs Importaciones",
#                         color_discrete_sequence=px.colors.sequential.RdBu)
# 
#     fig_global.update_layout(
#     paper_bgcolor="rgba(0,0,0,0)",
#     plot_bgcolor="rgba(0,0,0,0)",
#     font=dict(color="white"),
#     title=dict(font=dict(color="white")),
#     legend=dict(font=dict(color="white"))
#     )
# 
#     st.plotly_chart(fig_global, use_container_width=True)