# -*- coding: utf-8 -*-
"""styles.css

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmmtTSTrjNGklSGWi7i_cGBYHxV8DAO2
"""

header[data-testid="stHeader"] {
    display: none;
}

body {
    background-color: #0D1B2A;
}

.stApp {
    background-color: #0D1B2A;
}

html, body, p, span, div, label, h1, h2, h3, h4, h5, h6 {
    color: #E0E1DD;
}

h1, h2, h3 {
    font-weight: 700;
    color: #E0E1DD ;
}

.stSelectbox > div[data-baseweb="select"] {
    background-color: #3480eb !important;
    border-radius: 10px !important;
    border: 3px solid #0025f5 !important;
}

.stSelectbox > div[data-baseweb="select"] * {
    color: black !important;
}